# Generated by Django 3.2.9 on 2021-11-05 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='apto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(max_length=1, null=True)),
                ('apto', models.CharField(max_length=3, null=True)),
                ('id_pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moradores.pessoa')),
            ],
        ),
    ]
