# Generated by Django 3.2.9 on 2021-11-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0003_auto_20211105_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='apto',
        ),
        migrations.AddField(
            model_name='apto',
            name='id_pessoa',
            field=models.ManyToManyField(null=True, to='moradores.pessoa'),
        ),
    ]
