# Generated by Django 3.2.9 on 2021-11-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0005_auto_20211105_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('telefone', models.CharField(max_length=11, null=True)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('apto', models.ManyToManyField(null=True, to='moradores.apto')),
            ],
        ),
    ]
