# Generated by Django 3.2.9 on 2021-11-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0006_prestador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='apto',
            field=models.ManyToManyField(to='moradores.apto'),
        ),
    ]
