# Generated by Django 3.2.9 on 2021-11-22 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moradores', '0008_auto_20211122_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='apto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apto', models.CharField(max_length=3, null=True)),
                ('bloco', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('telefone', models.CharField(max_length=11, null=True)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apto', models.ManyToManyField(to='moradores.apto')),
                ('nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moradores.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField()),
                ('saída', models.DateTimeField(blank=True, null=True)),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moradores.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moradores.apto')),
                ('nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moradores.pessoa')),
            ],
        ),
    ]
