# Generated by Django 3.2.9 on 2021-11-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0009_apto_morador_movimento_pessoa_prestador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='morador',
            new_name='residente',
        ),
    ]
