# Generated by Django 3.2.9 on 2021-11-23 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0010_rename_morador_residente'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='apto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moradores.apto'),
        ),
    ]
